### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/Anagrams#1]
Add a basic README.md. Title and description should be enough.

**Comment by shiv4nsh** [comment]
@raj-subhankar :Assign this to me ! 
What else is needed here . can you please provide me the full flow ! Thanks

**Comment by raj-subhankar** [comment]
hi @shiv4nsh, @Emdix already finished this task, if you are interested you can look into issue #3. Comment there I will assign it to you.
