### ISSUE TITLE
Add Screenshots to README

### ISSUE THREAD

**Issue by raj-subhankar** [raj-subhankar/Anagrams#3]
Run app and add screenshots depicting app usage.

**Comment by johnfelixespinosa** [comment]
Hey Raj,

I think this is a good one for me to start!

**Comment by Melon-Bread** [comment]
I should be able to help you with this! :+1:   

Do you have a apk I can work with, or do you want me to build from source?

**Comment by raj-subhankar** [comment]
Don't have an apk, can you build it from source?

**Comment by benjamingarcia** [comment]
@Melon-Bread Do you continue on this issue? also, I can do it ;-)

**Comment by Melon-Bread** [comment]
@benjamingarcia go for it. Gradle keeps giving me issues when i try to build. I just want to make sure this guy gets his screenshots =]

**Comment by benjamingarcia** [comment]
ok! let's rock 👍

**Comment by benjamingarcia** [comment]
see  #4

**Comment by raj-subhankar** [comment]
@benjamingarcia thanks!
